### ISSUE TITLE
Add extends to @marshal_with_model

### ISSUE THREAD

**Issue by jelly** [anjianshi/flask-restful-extend#7]
It would be cool to add fields to marshal_with_model so I can extend the db fields with for example 
@marshal_with_model(MyModel, extends=[ { 'uri': fields.Url('user') } ]

**Comment by anjianshi** [comment]
Oh, let me have a look, thanks

**Comment by anjianshi** [comment]
Got it  ^_^ 
https://github.com/anjianshi/flask-restful-extend/commit/fad240e32b09d26795c4b3985e882add0e02203f
